<a href="https://colab.research.google.com/github/chaubeyarvind/DataAnalytics-NumPY/blob/main/DataAnalytics_Sep_26_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
print("Welcome to Data Analytics")

Welcome to Data Analytics


NumPy Array

In [5]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [9]:
import numpy as np

In [10]:
np.array(my_list)

array([1, 2, 3])

In [11]:
my_matrix =[[1,2,3], [4,5,6], [7,8,9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Try Some built-in Function of NumPy

In [16]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [19]:
  np.arange(0,10,5)

array([0, 5])

Zeros and One's generataion

In [20]:
np.zeros(3)

array([0., 0., 0.])