<a href="https://colab.research.google.com/github/chaubeyarvind/DataAnalytics-NumPY/blob/main/Tree_and_Forest_Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Implementation of Tree Method**

In [1]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

from sklearn.metrics import classification_report,confusion_matrix

from sklearn.model_selection import train_test_split

In [2]:
from google.colab import files
uploaded = files.upload()

Saving car_evaluation.csv to car_evaluation.csv


In [4]:
df = pd.read_csv('car_evaluation.csv')

In [74]:
df.head()

buy  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [75]:
#Renaming columns names in the given data set.
new_col_names = ['buy', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [76]:
df.columns = new_col_names

In [77]:
df.head()

buy  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [78]:
df['class'].value_counts()

unacc    1209
acc       384
good       69
vgood      65
Name: class, dtype: int64

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buy       1727 non-null   object
 1   maint     1727 non-null   object
 2   doors     1727 non-null   object
 3   persons   1727 non-null   object
 4   lug_boot  1727 non-null   object
 5   safety    1727 non-null   object
 6   class     1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [80]:
X = df.drop('class', axis = 1)
y = df['class']

In [81]:
mapping = [{'col':'buy', 'mapping':{'low':0, 'med':1, 'high':2, 'vhigh':3}},

          {'col':'maint', 'mapping':{'low':0, 'med':1, 'high':2, 'vhigh':3}},

          {'col':'doors', 'mapping':{'2':0, '3':1, '4':2, '5more':3}},

          {'col':'persons', 'mapping':{'2':0, '4':1, 'more':2}},

          {'col':'lug_boot', 'mapping':{'small':0, 'med':1, 'big':2}},

          {'col':'safety', 'mapping':{'low':0, 'med':1, 'high':2}}]

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=101)

In [83]:
encoder = ce.OrdinalEncoder(cols=['byuing', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], mapping = mapping)



X_train = encoder.fit_transform(X_train)

X_test = encoder.fit_transform(X_test)

In [84]:
! pip install --upgrade category_encoders
import category_encoders as ce

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [85]:
encoder = ce.OrdinalEncoder(cols=['buy', 'maint', 'doors', 'persons', 'lug_boot', 'safety'])

In [86]:
X.head()

buy  maint doors persons lug_boot safety
0  vhigh  vhigh     2       2    small    med
1  vhigh  vhigh     2       2    small   high
2  vhigh  vhigh     2       2      med    low
3  vhigh  vhigh     2       2      med    med
4  vhigh  vhigh     2       2      med   high

In [87]:
X_train = encoder.fit_transform(X_train)
X_test = encoder.fit_transform(X_test)

In [88]:
X_train.head()

buy  maint  doors  persons  lug_boot  safety
1633    1      1      1        1         1       1
1237    2      1      2        2         1       1
395     3      1      3        2         2       2
770     4      1      1        1         3       2
1321    1      2      1        2         3       1

In [89]:
X_test.head()

buy  maint  doors  persons  lug_boot  safety
157     1      1      1        1         1       1
460     2      2      1        2         2       1
669     2      3      2        1         1       2
1331    3      2      1        3         2       3
1337    3      2      1        3         3       3

In [90]:
from sklearn.tree import DecisionTreeClassifier

In [106]:
dtree = DecisionTreeClassifier()

In [107]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier()

In [108]:
predictions = dtree.predict(X_test)

In [109]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         acc       0.12      0.14      0.13       146
        good       0.00      0.00      0.00        28
       unacc       0.67      0.65      0.66       492
       vgood       0.00      0.00      0.00        25

    accuracy                           0.49       691
   macro avg       0.20      0.20      0.20       691
weighted avg       0.50      0.49      0.50       691



In [110]:
print(confusion_matrix(y_test, predictions))

[[ 20   1 118   7]
 [  2   0  26   0]
 [136  20 322  14]
 [ 12   0  13   0]]


In [111]:
from sklearn import tree
text_pre = tree.export_text(dtree)
print(text_pre)

|--- feature_3 <= 2.50
|   |--- feature_5 <= 1.50
|   |   |--- feature_0 <= 2.50
|   |   |   |--- feature_1 <= 1.50
|   |   |   |   |--- feature_4 <= 2.50
|   |   |   |   |   |--- feature_4 <= 1.50
|   |   |   |   |   |   |--- feature_2 <= 1.50
|   |   |   |   |   |   |   |--- class: good
|   |   |   |   |   |   |--- feature_2 >  1.50
|   |   |   |   |   |   |   |--- feature_2 <= 2.50
|   |   |   |   |   |   |   |   |--- feature_3 <= 1.50
|   |   |   |   |   |   |   |   |   |--- class: good
|   |   |   |   |   |   |   |   |--- feature_3 >  1.50
|   |   |   |   |   |   |   |   |   |--- class: vgood
|   |   |   |   |   |   |   |--- feature_2 >  2.50
|   |   |   |   |   |   |   |   |--- class: vgood
|   |   |   |   |   |--- feature_4 >  1.50
|   |   |   |   |   |   |--- feature_2 <= 1.50
|   |   |   |   |   |   |   |--- feature_3 <= 1.50
|   |   |   |   |   |   |   |   |--- class: good
|   |   |   |   |   |   |   |--- feature_3 >  1.50
|   |   |   |   |   |   |   |   |--- class: unacc
|  

In [112]:
from sklearn.ensemble import RandomForestClassifier

In [113]:
rfc = RandomForestClassifier()

In [114]:
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [115]:
prediction_rf = rfc.predict(X_test)

In [116]:
print(confusion_matrix(y_test, prediction_rf))

[[ 22   1 117   6]
 [  2   0  26   0]
 [141  19 320  12]
 [ 13   0  12   0]]


In [117]:
print(classification_report(y_test, prediction_rf))

              precision    recall  f1-score   support

         acc       0.12      0.15      0.14       146
        good       0.00      0.00      0.00        28
       unacc       0.67      0.65      0.66       492
       vgood       0.00      0.00      0.00        25

    accuracy                           0.49       691
   macro avg       0.20      0.20      0.20       691
weighted avg       0.51      0.49      0.50       691

