<a href="https://colab.research.google.com/github/chaubeyarvind/DataAnalytics-NumPY/blob/main/Tree_and_Forest_Methods.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Implementation of Tree Method**

In [1]:
import pandas as pd

import numpy as np

import matplotlib.pyplot as plt

import seaborn as sns

from sklearn.metrics import classification_report,confusion_matrix

from sklearn.model_selection import train_test_split

In [2]:
from google.colab import files
uploaded = files.upload()

Saving car_evaluation.csv to car_evaluation.csv


In [4]:
df = pd.read_csv('car_evaluation.csv')

In [6]:
df.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [8]:
#Renaming columns names in the given data set.
new_col_names = ['buy', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']

In [9]:
df.columns = new_col_names

In [10]:
df.head()

buy  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [11]:
df['class'].value_counts()

unacc    1209
acc       384
good       69
vgood      65
Name: class, dtype: int64

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buy       1727 non-null   object
 1   maint     1727 non-null   object
 2   doors     1727 non-null   object
 3   persons   1727 non-null   object
 4   lug_boot  1727 non-null   object
 5   safety    1727 non-null   object
 6   class     1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [13]:
X = df.drop('class', axis = 1)
y = df['class']

In [36]:
mapping = [{'col':'buy', 'mapping':{'low':0, 'med':1, 'high':2, 'vhigh':3}},

          {'col':'maint', 'mapping':{'low':0, 'med':1, 'high':2, 'vhigh':3}},

          {'col':'doors', 'mapping':{'2':0, '3':1, '4':2, '5more':3}},

          {'col':'persons', 'mapping':{'2':0, '4':1, 'more':2}},

          {'col':'lug_boot', 'mapping':{'small':0, 'med':1, 'big':2}},

          {'col':'safety', 'mapping':{'low':0, 'med':1, 'high':2}}]

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=101)

In [55]:
encoder = ce.OrdinalEncoder(cols=['byuing', 'maint', 'doors', 'persons', 'lug_boot', 'safety'], mapping = mapping)



X_train = encoder.fit_transform(X_train)

X_test = encoder.fit_transform(X_test)

In [15]:
! pip install --upgrade category_encoders
import category_encoders as ce

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 69 kB 1.9 MB/s 


In [56]:
encoder = ce.OrdinalEncoder(cols=['buy', 'maint', 'doors', 'persons', 'lug_boot', 'safety'])

In [57]:
X.head()

buy  maint doors persons lug_boot safety
0  vhigh  vhigh     2       2    small    med
1  vhigh  vhigh     2       2    small   high
2  vhigh  vhigh     2       2      med    low
3  vhigh  vhigh     2       2      med    med
4  vhigh  vhigh     2       2      med   high

In [58]:
X_train = encoder.fit_transform(X_train)
X_test = encoder.fit_transform(X_test)

In [59]:
X_train.head()

buy  maint  doors  persons  lug_boot  safety
1633    1      1      1        1         1       1
1237    1      1      1        1         1       1
395     1      1      1        1         1       1
770     1      1      1        1         1       1
1321    1      1      1        1         1       1

In [60]:
X_test.head()

buy  maint  doors  persons  lug_boot  safety
157     1      1      1        1         1       1
460     1      1      1        1         1       1
669     1      1      1        1         1       1
1331    1      1      1        1         1       1
1337    1      1      1        1         1       1

In [61]:
from sklearn.tree import DecisionTreeClassifier

In [62]:
dtree = DecisionTreeClassifier(max_depth=3)

In [63]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3)

In [64]:
predictions = dtree.predict(X_test)

In [65]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         acc       0.00      0.00      0.00       146
        good       0.00      0.00      0.00        28
       unacc       0.71      1.00      0.83       492
       vgood       0.00      0.00      0.00        25

    accuracy                           0.71       691
   macro avg       0.18      0.25      0.21       691
weighted avg       0.51      0.71      0.59       691



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [66]:
print(confusion_matrix(y_test, predictions))

[[  0   0 146   0]
 [  0   0  28   0]
 [  0   0 492   0]
 [  0   0  25   0]]


In [67]:
from sklearn import tree
text_pre = tree.export_text(dtree)
print(text_pre)

|--- class: unacc



In [68]:
from sklearn.ensemble import RandomForestClassifier

In [69]:
rfc = RandomForestClassifier()

In [70]:
rfc.fit(X_train, y_train)

RandomForestClassifier()

In [71]:
prediction_rf = rfc.predict(X_test)

In [72]:
print(confusion_matrix(y_test, prediction_rf))

[[  0   0 146   0]
 [  0   0  28   0]
 [  0   0 492   0]
 [  0   0  25   0]]


In [73]:
print(classification_report(y_test, prediction_rf))

              precision    recall  f1-score   support

         acc       0.00      0.00      0.00       146
        good       0.00      0.00      0.00        28
       unacc       0.71      1.00      0.83       492
       vgood       0.00      0.00      0.00        25

    accuracy                           0.71       691
   macro avg       0.18      0.25      0.21       691
weighted avg       0.51      0.71      0.59       691



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
